baseURL = "https://stausa.github.io/"
languageCode = "en-us"
title = "Stausa Art Studio"
publishDir = "docs"

[menu]

  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 10
    
  [[menu.main]]
    parent = "gallery"
    name = "barche"
    url = "/gallery/barche/"
    
  [[menu.main]]
    parent = "gallery"
    name = "pupazzi"
    url = "/gallery/pupazzi/"

  [[menu.main]]
    identifier = "exhibitions"
    name = "Exhibitions"
    url = "/exhibitions/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40